// THIS FILE IS AUTOGENERATED. DO NOT EDIT MANUALLY.
// Run the generation script to regenerate.

export interface Home {
  pageTitle: string;
  intro: string;
  learnMore: string;
  複雑なキー_with_underscore: string;
}

export interface Common {
  appName: string;
  greeting: string;
  greetingWithName: string;
  welcomeMessage: string;
  items_one: string;
  items_other: string;
  languageLabel: string;
  selectLanguage: string;
  navigation: {
    home: string;
    about: string;
    contact: string;
    dashboard: string;
    clientPage: string;
  };
  direction: string;
}

export interface Resources {
  home: Home;
  common: Common;
}
